In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file_path = "C:/Users/Samsung/Downloads/cleaned_german_credit_data.csv"  # replace with your file path
df = pd.read_csv(file_path)
# Iterate through each column and print unique responses
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique responses for '{column}':")
    print(unique_values)
    print(f"Count: {len(unique_values)}\n")

Unique responses for 'Age':
[22 45 53 35 28 25 24 60 32 44 48 36 42 34 63 27 30 33 37 26 58 23 57 61
 51 41 66 52 47 54 39 31 40 29 20 38 70 65 74 68 21 50 46 55 49 56 75 19
 43 67 64 59]
Count: 52

Unique responses for 'Sex':
[1 0]
Count: 2

Unique responses for 'Job':
[2 3 1 0]
Count: 4

Unique responses for 'Housing':
['own' 'free' 'rent']
Count: 3

Unique responses for 'Saving accounts':
['little' 'moderate' 'quite rich' 'rich']
Count: 4

Unique responses for 'Checking account':
['moderate' 'little' 'rich']
Count: 3

Unique responses for 'Credit amount':
[ 5951  7882  4870  6948  5234  1295  4308  1567  1199  1403  1282 12579
  2647  2241  1804  1374   409  2415  6836  1913  4020  5866  1474  4746
  2100  1225   458  1158  6204  6187  6143  1352  5965  2225  1961  6229
  1391  1953 14421  1007  1164  5954  1526  3965  4771  3832  1755  2315
 12612  2249  1108  1409  1318 15945  2622  2337  2323  1919 11938  6078
  1410  1449   392  6260  1680  4281  2366  1835   781  2121   701   639
  1860  3499  6887   766  1881   709  4795  3416  2462  3566   860  5371
  5848  7758  6967  1288   339  3512  7308  1131  1577  1935   950  2064
  1414  3414  2577   338   571  4455   884  5129  1175   674  3244  3844
  3915  3031  1501   951  4297  1168   902 10623  1424  6568  5293  1908
  3104  3913  3021   625 10961  7865  3149  4210   866  1823  2767  2522
  4605  1925   666  2251  2150  2149  1657  1603  5302   802  8978  3060
 11998  3878 10722  4788  7582  1092  1024  9398  6419  4796  9960  2745
  3804  1038   727  1237   276  3749   685  2746   708  3643  4249  1938
  2910  2659  3398  4473  1068  6615  7408  4110  3384  2101  4169  1521
  5743  3599  3213  4439  3949   882  3758  1136   959  6199  1246  2406
  2247  2473  3650  3446  3001 14782  7685 14318 12976  1330  7374  2326
   983  3249  1957 11760  2578  2348  1223  2039  1053   939  1967  2579
   958  2779  1190 11328  1872  2136  3394   609  1620  2629  5096  1842
  2576  1512  4817  3905  3386   343  3620  1721  3017  2924  1659  3092
   448   654  1245  3114  5152  1037  1478  3573  1201  3622  1209  8318
  2122  9034  1301  1323  3123  5493  1126  1216  1207  2360  6850   759
  2687   585  1361  1203  3190  7119  1113  7966  2302   662  2273  2631
  2319  3612  7763  3049  1534  2864  1333   626  6999  1995  1331  2278
  3552  1928  1546   683  1553  1372  6758  3234   806  1082  2930  2820
  1056  3124  2384  2799  1289  1217  2246   385  2718   931  1442  4241
  2329   918  1837  1275  2828  2671   741  1240  3357  3632  3676  3441
  3652  1858  2600  2116  1437  3660  1355  4370   750  1308  1880  4583
   947   684  7476  1922  2303  8086  3973   888  4221  6361  1297  1050
  1047  3496  4843  5595  9857  2862  3651   975  2896  1103  1905  6331
  1377  2503  2528  6560  2969  1206  2118  1198  1138 14027  6148  1337
   433  1228   790  1882  6416  6403  1987   760 11560  4380  4280  2325
  1048  2483  1797  2511  1274   428   976   841  1299   691  2124  2214
  1155  3108  3617  8065  1480  3509  3872  4933   836  1941  6224  5998
  1188  2892  1795  4272  9271   590  9283  1778   907   484  9629  3051
  3931  7432 15857  1345  3016  2712   731  1602  3966 11816  2327  2957
  5179  1364  2235  3959  2439  2389   652  1343  1382  3590  1322  1940
  1422  4057   795 15672  2442  2171  5800  2606  4153  2625  1107  4736
  3161 18424 14896  2359  3345  1366  2002  6872   697  1049 10297  1344
  1747  1670  1498   745  2063  6288  1845  8358  3349  2145  4113  1893
  1231  1154  4006  3069  2353   454  2520  3939  1514  1193  7297  1258
   753  1264  8386  2923  8229  1433  6289  6579  1743  3857  4576]
Count: 503

Unique responses for 'Duration':
[48 42 24 36 30 12 15  6 10  7 60 18 45  9 27  8 11 54 14 33 21 16 47 13
 39 20 26 72 40 28]
Count: 30

Unique responses for 'Purpose':
['radio/TV' 'furniture/equipment' 'car' 'business' 'domestic appliances'
 'repairs' 'vacation/others' 'education']
Count: 8

Unique responses for 'Risk':
['bad' 'good']
Count: 2

In [3]:
df['Risk'] = df['Risk'].replace({'bad': 0, 'good': 1})
df['Saving accounts'] = df['Saving accounts'].replace({'little': 0, 'moderate': 1, 'quite rich': 2, 'rich': 3})
df['Checking account'] = df['Checking account'].replace({'little': 0, 'moderate': 1, 'rich': 2})

C:\Users\Samsung\AppData\Local\Temp\ipykernel_26928\3298219706.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Risk'] = df['Risk'].replace({'bad': 0, 'good': 1})
C:\Users\Samsung\AppData\Local\Temp\ipykernel_26928\3298219706.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Saving accounts'] = df['Saving accounts'].replace({'little': 0, 'moderate': 1, 'quite rich': 2, 'rich': 3})
C:\Users\Samsung\AppData\Local\Temp\ipykernel_26928\3298219706.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Checking account'] = df['Checking account'].replace({'little': 0, 'moderate': 1, 'rich': 2})

In [4]:
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique responses for '{column}':")
    print(unique_values)
    print(f"Count: {len(unique_values)}\n")

Unique responses for 'Age':
[22 45 53 35 28 25 24 60 32 44 48 36 42 34 63 27 30 33 37 26 58 23 57 61
 51 41 66 52 47 54 39 31 40 29 20 38 70 65 74 68 21 50 46 55 49 56 75 19
 43 67 64 59]
Count: 52

Unique responses for 'Sex':
[1 0]
Count: 2

Unique responses for 'Job':
[2 3 1 0]
Count: 4

Unique responses for 'Housing':
['own' 'free' 'rent']
Count: 3

Unique responses for 'Saving accounts':
[0 1 2 3]
Count: 4

Unique responses for 'Checking account':
[1 0 2]
Count: 3

Unique responses for 'Credit amount':
[ 5951  7882  4870  6948  5234  1295  4308  1567  1199  1403  1282 12579
  2647  2241  1804  1374   409  2415  6836  1913  4020  5866  1474  4746
  2100  1225   458  1158  6204  6187  6143  1352  5965  2225  1961  6229
  1391  1953 14421  1007  1164  5954  1526  3965  4771  3832  1755  2315
 12612  2249  1108  1409  1318 15945  2622  2337  2323  1919 11938  6078
  1410  1449   392  6260  1680  4281  2366  1835   781  2121   701   639
  1860  3499  6887   766  1881   709  4795  3416  2462  3566   860  5371
  5848  7758  6967  1288   339  3512  7308  1131  1577  1935   950  2064
  1414  3414  2577   338   571  4455   884  5129  1175   674  3244  3844
  3915  3031  1501   951  4297  1168   902 10623  1424  6568  5293  1908
  3104  3913  3021   625 10961  7865  3149  4210   866  1823  2767  2522
  4605  1925   666  2251  2150  2149  1657  1603  5302   802  8978  3060
 11998  3878 10722  4788  7582  1092  1024  9398  6419  4796  9960  2745
  3804  1038   727  1237   276  3749   685  2746   708  3643  4249  1938
  2910  2659  3398  4473  1068  6615  7408  4110  3384  2101  4169  1521
  5743  3599  3213  4439  3949   882  3758  1136   959  6199  1246  2406
  2247  2473  3650  3446  3001 14782  7685 14318 12976  1330  7374  2326
   983  3249  1957 11760  2578  2348  1223  2039  1053   939  1967  2579
   958  2779  1190 11328  1872  2136  3394   609  1620  2629  5096  1842
  2576  1512  4817  3905  3386   343  3620  1721  3017  2924  1659  3092
   448   654  1245  3114  5152  1037  1478  3573  1201  3622  1209  8318
  2122  9034  1301  1323  3123  5493  1126  1216  1207  2360  6850   759
  2687   585  1361  1203  3190  7119  1113  7966  2302   662  2273  2631
  2319  3612  7763  3049  1534  2864  1333   626  6999  1995  1331  2278
  3552  1928  1546   683  1553  1372  6758  3234   806  1082  2930  2820
  1056  3124  2384  2799  1289  1217  2246   385  2718   931  1442  4241
  2329   918  1837  1275  2828  2671   741  1240  3357  3632  3676  3441
  3652  1858  2600  2116  1437  3660  1355  4370   750  1308  1880  4583
   947   684  7476  1922  2303  8086  3973   888  4221  6361  1297  1050
  1047  3496  4843  5595  9857  2862  3651   975  2896  1103  1905  6331
  1377  2503  2528  6560  2969  1206  2118  1198  1138 14027  6148  1337
   433  1228   790  1882  6416  6403  1987   760 11560  4380  4280  2325
  1048  2483  1797  2511  1274   428   976   841  1299   691  2124  2214
  1155  3108  3617  8065  1480  3509  3872  4933   836  1941  6224  5998
  1188  2892  1795  4272  9271   590  9283  1778   907   484  9629  3051
  3931  7432 15857  1345  3016  2712   731  1602  3966 11816  2327  2957
  5179  1364  2235  3959  2439  2389   652  1343  1382  3590  1322  1940
  1422  4057   795 15672  2442  2171  5800  2606  4153  2625  1107  4736
  3161 18424 14896  2359  3345  1366  2002  6872   697  1049 10297  1344
  1747  1670  1498   745  2063  6288  1845  8358  3349  2145  4113  1893
  1231  1154  4006  3069  2353   454  2520  3939  1514  1193  7297  1258
   753  1264  8386  2923  8229  1433  6289  6579  1743  3857  4576]
Count: 503

Unique responses for 'Duration':
[48 42 24 36 30 12 15  6 10  7 60 18 45  9 27  8 11 54 14 33 21 16 47 13
 39 20 26 72 40 28]
Count: 30

Unique responses for 'Purpose':
['radio/TV' 'furniture/equipment' 'car' 'business' 'domestic appliances'
 'repairs' 'vacation/others' 'education']
Count: 8

Unique responses for 'Risk':
[0 1]
Count: 2

In [48]:
nominal_columns = df.select_dtypes(include=['object']).columns.tolist()

# One-hot encode the nominal columns
df_one_hot = pd.get_dummies(df, columns=nominal_columns, drop_first=True)

# Display the transformed DataFrame
print("\nOne-Hot Encoded DataFrame:")
print(df_one_hot)

One-Hot Encoded DataFrame:
     Age  Sex  Job  Saving accounts  Checking account  Credit amount  \
0     22    1    2                0                 1           5951
1     45    0    2                0                 0           7882
2     53    0    2                0                 0           4870
3     35    0    3                0                 1           6948
4     28    0    3                0                 1           5234
..   ...  ...  ...              ...               ...            ...
517   48    0    1                0                 1           1743
518   30    0    3                0                 0           3959
519   40    0    3                0                 0           3857
520   23    0    2                0                 0           1845
521   27    0    2                1                 1           4576

     Duration  Risk  Housing_own  Housing_rent  Purpose_car  \
0          48     0         True         False        False
1          42     1        False         False        False
2          24     0        False         False         True
3          36     1        False          True         True
4          30     0         True         False         True
..        ...   ...          ...           ...          ...
517        24     1         True         False        False
518        36     1         True         False        False
519        30     1         True         False         True
520        45     0        False         False        False
521        45     1         True         False         True

     Purpose_domestic appliances  Purpose_education  \
0                          False              False
1                          False              False
2                          False              False
3                          False              False
4                          False              False
..                           ...                ...
517                        False              False
518                        False              False
519                        False              False
520                        False              False
521                        False              False

     Purpose_furniture/equipment  Purpose_radio/TV  Purpose_repairs  \
0                          False              True            False
1                           True             False            False
2                          False             False            False
3                          False             False            False
4                          False             False            False
..                           ...               ...              ...
517                        False              True            False
518                         True             False            False
519                        False             False            False
520                        False              True            False
521                        False             False            False

     Purpose_vacation/others
0                      False
1                      False
2                      False
3                      False
4                      False
..                       ...
517                    False
518                    False
519                    False
520                    False
521                    False

[522 rows x 17 columns]

In [49]:
# Check the data types of each column
data_types = df_one_hot.dtypes

# Print the data types
print(data_types)

Age                            int64
Sex                            int64
Job                            int64
Saving accounts                int64
Checking account               int64
Credit amount                  int64
Duration                       int64
Risk                           int64
Housing_own                     bool
Housing_rent                    bool
Purpose_car                     bool
Purpose_domestic appliances     bool
Purpose_education               bool
Purpose_furniture/equipment     bool
Purpose_radio/TV                bool
Purpose_repairs                 bool
Purpose_vacation/others         bool
dtype: object

In [50]:
risk = df_one_hot.pop('Risk')
df_one_hot.insert(len(df_one_hot.columns), 'Risk', risk)

In [51]:
# Convert boolean columns to integers (1 for True, 0 for False)
boolean_columns = df_one_hot.select_dtypes(include=['bool']).columns.tolist()

for column in boolean_columns:
    df_one_hot[column] = df_one_hot[column].astype(int)

# Display the transformed DataFrame
print("\nDataFrame with Boolean Columns Converted to Integers:")
print(df_one_hot)

DataFrame with Boolean Columns Converted to Integers:
     Age  Sex  Job  Saving accounts  Checking account  Credit amount  \
0     22    1    2                0                 1           5951
1     45    0    2                0                 0           7882
2     53    0    2                0                 0           4870
3     35    0    3                0                 1           6948
4     28    0    3                0                 1           5234
..   ...  ...  ...              ...               ...            ...
517   48    0    1                0                 1           1743
518   30    0    3                0                 0           3959
519   40    0    3                0                 0           3857
520   23    0    2                0                 0           1845
521   27    0    2                1                 1           4576

     Duration  Housing_own  Housing_rent  Purpose_car  \
0          48            1             0            0
1          42            0             0            0
2          24            0             0            1
3          36            0             1            1
4          30            1             0            1
..        ...          ...           ...          ...
517        24            1             0            0
518        36            1             0            0
519        30            1             0            1
520        45            0             0            0
521        45            1             0            1

     Purpose_domestic appliances  Purpose_education  \
0                              0                  0
1                              0                  0
2                              0                  0
3                              0                  0
4                              0                  0
..                           ...                ...
517                            0                  0
518                            0                  0
519                            0                  0
520                            0                  0
521                            0                  0

     Purpose_furniture/equipment  Purpose_radio/TV  Purpose_repairs  \
0                              0                 1                0
1                              1                 0                0
2                              0                 0                0
3                              0                 0                0
4                              0                 0                0
..                           ...               ...              ...
517                            0                 1                0
518                            1                 0                0
519                            0                 0                0
520                            0                 1                0
521                            0                 0                0

     Purpose_vacation/others  Risk
0                          0     0
1                          0     1
2                          0     0
3                          0     1
4                          0     0
..                       ...   ...
517                        0     1
518                        0     1
519                        0     1
520                        0     0
521                        0     1

[522 rows x 17 columns]

In [53]:
# Output df_cleaned to a CSV file
df_one_hot.to_csv('C:/Users/Samsung/Downloads/cleaned_german_credit_data_updated.csv', index=False)